apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-static-pvc
  namespace: rpgmap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
